# Generated by Django 6.1 on 2026-09-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_quiz_quizattempt_quizquestion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quizattempt',
            name='unique_student_quiz_attempt',
        ),
    ]
