# Generated by Django 6.1 on 2026-09-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_examination_examattempt_examquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='manual_grades',
            field=models.JSONField(default=dict),
        ),
    ]
