# Generated by Django 6.1 on 2026-09-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='lessons/videos/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='lessons/pdfs/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='lessons/audio/')),
                ('external_resource', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('course', 'order'), name='unique_lesson_order_per_course')],
            },
        ),
    ]
