"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!

SECRET_KEY = config("SECRET_KEY")

DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="127.0.0.1,localhost",
).split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "drf_spectacular",
    "corsheaders",
    # My apps
    "accounts",
    "courses",
    "enrollments",
    "assessments",
    "notifications",
    "reviews",
    "analytics",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}

AUTH_USER_MODEL = "accounts.User"
# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Email
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool)

EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default=EMAIL_HOST_USER,
)

BACKEND_URL = config(
    "BACKEND_URL",
    default="http://127.0.0.1:8000",
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Education LMS API",
    "DESCRIPTION": """
REST API for an Education Learning Management System.

The API provides functionality for:

- User authentication and authorization
- Course management
- Lessons and lesson completion
- Student enrollments
- Assignments and grading
- Quizzes and examinations
- Certificates
- Reviews and ratings
- Notifications
- Learning analytics

Authentication is handled using JWT bearer tokens.

The deployed demonstration uses seeded Admin, Instructor, and Student accounts.
Use the interactive Authorize button with a valid access token to call protected endpoints.
The Swagger UI keeps authorization state during the current browser session.

The API returns ordinary JSON arrays for list endpoints; pagination is not enabled.
""",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SERVERS": [
        {
            "url": "https://lms-project-aj6m.onrender.com",
            "description": "Hosted Render demo",
        },
        {
            "url": "http://127.0.0.1:8000",
            "description": "Local development server",
        },
    ],
    "TAGS": [
        {
            "name": "auth",
            "description": "Registration, authentication, verification, password reset, and instructor onboarding.",
        },
        {
            "name": "profile",
            "description": "Authenticated user profile operations.",
        },
        {
            "name": "courses",
            "description": "Course discovery and course management.",
        },
        {
            "name": "categories",
            "description": "Course category management.",
        },
        {
            "name": "lessons",
            "description": "Lesson management and completion tracking.",
        },
        {
            "name": "enrollments",
            "description": "Student course enrollment operations.",
        },
        {
            "name": "assignments",
            "description": "Assignment creation and management.",
        },
        {
            "name": "submissions",
            "description": "Assignment submission and grading operations.",
        },
        {
            "name": "quizzes",
            "description": "Quiz management and question access.",
        },
        {
            "name": "quiz-questions",
            "description": "Quiz question management.",
        },
        {
            "name": "quiz-attempts",
            "description": "Quiz attempt lifecycle and submission.",
        },
        {
            "name": "examinations",
            "description": "Scheduled examination management and question access.",
        },
        {
            "name": "exam-questions",
            "description": "Examination question management.",
        },
        {
            "name": "exam-attempts",
            "description": "Examination attempt lifecycle and manual grading.",
        },
        {
            "name": "grades",
            "description": "Aggregated assignment, quiz, and examination grades.",
        },
        {
            "name": "results",
            "description": "Calculated course-level results.",
        },
        {
            "name": "certificates",
            "description": "Course certificate issuance and management.",
        },
        {
            "name": "notifications",
            "description": "Authenticated notification inbox and read-state management.",
        },
        {
            "name": "reviews",
            "description": "Course reviews and rating summaries.",
        },
        {
            "name": "analytics",
            "description": "Role-specific learning and platform analytics.",
        },
    ],
    # JWT authentication
    "SECURITY": [
        {
            "bearerAuth": [],
        }
    ],
    "COMPONENTS": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },
}

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
