# Generated by Django 6.1 on 2026-09-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ENROLLMENT', 'Enrollment'), ('ASSIGNMENT_SUBMISSION', 'Assignment Submission'), ('EXAM_SUBMISSION', 'Examination Submission'), ('ASSIGNMENT_REMINDER', 'Assignment Reminder'), ('EXAM_REMINDER', 'Examination Reminder'), ('GRADE', 'Grade'), ('CERTIFICATE', 'Certificate'), ('GENERAL', 'General')], max_length=30),
        ),
    ]
